// ---- deps in Cargo.toml ----
// p256   = { version = "0.13", features = ["ecdsa"] }
// ecdsa  = "0.14"                  # pulled in by p256, re-exported
// sha2   = "0.10"
// rand_core = "0.6"                # only needed by the test below
// --------------------------------

use p256::{
    ecdsa::{
        signature::{Signer, Verifier},   // traits
        Signature, SigningKey, VerifyingKey,
    },
    EncodedPoint,
};

/// Sign `message` with a raw 32-byte NIST-P256 secret key.
/// The returned signature is **DER-encoded** (same format as Python’s
/// `ecdsa` library).
pub fn sign_nist256(message: &[u8], signing_key_raw: &[u8]) -> Vec<u8> {
    // Python hands us a 32-byte big-endian scalar.
    let signing_key =
        SigningKey::from_bytes(signing_key_raw).expect("private key must be 32 bytes (P-256)");

    // `Signer::sign` uses deterministic RFC-6979 ECDSA with SHA-256 for P-256.
    let sig: Signature = signing_key.sign(message);

    sig.to_der().as_bytes().to_vec()
}

/// Verify a signature generated by `sign_nist256`.
///
/// * `verifying_key_raw` must be the **64 raw bytes** (X‖Y) returned by
///   Python’s `ecdsa.VerifyingKey.to_string()`.
/// * `signature` must be the DER-encoded bytes returned by `sign_nist256`.
pub fn verify_nist256(
    message: &[u8],
    signature: &[u8],
    verifying_key_raw: &[u8],
) -> bool {
    // Re-create an uncompressed SEC1 public key: 0x04 || X || Y
    if verifying_key_raw.len() != 64 {
        return false;
    }
    let mut buf = [0u8; 65];
    buf[0] = 0x04;
    buf[1..].copy_from_slice(verifying_key_raw);

    let point = match EncodedPoint::from_bytes(&buf) {
        Ok(p) => p,
        Err(_) => return false,
    };

    let verifying_key = match VerifyingKey::from_encoded_point(&point) {
        Ok(k) => k,
        Err(_) => return false,
    };

    // Parse the DER signature produced by `sign_nist256`.
    let sig = match Signature::from_der(signature) {
        Ok(s) => s,
        Err(_) => return false,
    };

    verifying_key.verify(message, &sig).is_ok()
}

/* ------------------------------------------------------------------ */
/* A quick round-trip test (cargo test)                               */
/* ------------------------------------------------------------------ */
#[cfg(test)]
mod tests {
    use super::*;
    use p256::ecdsa::SigningKey;
    use rand_core::OsRng;

    #[test]
    fn round_trip() {
        // random keypair
        let signing_key = SigningKey::random(&mut OsRng);
        let verifying_key = signing_key.verifying_key();

        // make the raw 64-byte public key (same layout as Python)
        let raw_pub = &verifying_key.to_encoded_point(false).as_bytes()[1..]; // skip 0x04

        let msg = b"hello from rust";

        let sig = sign_nist256(msg, &signing_key.to_bytes());
        assert!(verify_nist256(msg, &sig, raw_pub));

        // wrong message → should fail
        assert!(!verify_nist256(b"tampered", &sig, raw_pub));
    }
}