/*
 *  Example that mimics the behaviour of the original Python snippet.
 *  All the headers / data-types referenced below are assumed to be
 *  supplied by the same “ellipticcurve” C SDK that accompanies the
 *  Python package you used.  Nothing here relies on any non-standard
 *  library that you need to worry about.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*  ----  Elliptic-curve headers (provided elsewhere)  ---- */
#include "ellipticcurve/ecdsa.h"      /*  Ecdsa_sign, Signature, …   */
#include "ellipticcurve/privateKey.h" /*  PrivateKey, PublicKey, …   */


/* --------------------------------------------------------- */
/*            Equivalent of generate_ecdsa_signed_msg()      */
/* --------------------------------------------------------- */
static Signature *generate_ecdsa_signed_msg(const char *message,
                                            PrivateKey       *priv_key)
{
    /*  The C binding is assumed to mirror the Python API:           *
     *      Signature *Ecdsa_sign(const char *msg, PrivateKey *key); */
    return Ecdsa_sign(message, priv_key);
}


/* --------------------------------------------------------- */
/*                           main()                          */
/* --------------------------------------------------------- */
int main(void)
{
    /* ---- 1) Generate a new key-pair --------------------- */
    PrivateKey *priv_key = PrivateKey_new();  /* allocate & generate */
    PublicKey  *pub_key  = PrivateKey_publicKey(priv_key);

    /* ---- 2) Sign a message ------------------------------ */
    const char *message = "My test message";
    Signature  *sig     = generate_ecdsa_signed_msg(message, priv_key);

    /* ---- 3) Print / serialise the signature ------------- *
     * A helper that returns a textual representation is     *
     * expected to exist; we’ll call it Signature_toString().*/
    char *sig_str = Signature_toString(sig);
    printf("%s\n", sig_str);

    /* ---- 4) House-keeping -------------------------------- */
    free(sig_str);             /* string generated by Signature_toString    */
    Signature_free(sig);       /* release signature structure               */
    PublicKey_free(pub_key);   /* release public key                        */
    PrivateKey_free(priv_key); /* release private key                       */

    return 0;
}